"""Core data structures and interfaces for the Rodin Frame Engine.

This module defines the fundamental building blocks of the frame system, including
the abstract `Frame` class that all frames must implement, and the `FrameContext`
TypedDict that carries state through the processing pipeline.

Note: Frame-specific data models (shared context keys, enums, TypedDicts) are
defined in their respective frame modules and exported from backend.frames.
"""
from abc import ABC, abstractmethod
from datetime import datetime
from enum import Enum
import json
import sys
from pathlib import Path
from typing import Any, Optional, TypedDict

import yaml


class TerminalLogger:
    """Captures terminal output to both console and file.
    
    This utility class can be used to log all stdout and stderr output to a file
    while still displaying it in the terminal. Useful for simulations
    and CLI tools that need to capture their output, including warnings and errors.
    """
    
    def __init__(self, log_file_path: str, stream=None, shared_file=None):
        """Initialize the terminal logger.
        
        Args:
            log_file_path: Path to the file where output will be logged.
            stream: The original stream (stdout or stderr) to also write to.
                    If None, will use sys.stdout as default.
            shared_file: Optional file handle to share between multiple loggers.
                        If provided, this logger will use the shared file instead
                        of opening a new one.
        """
        if shared_file is not None:
            self.log_file = shared_file
            self._should_close = False
        else:
            self.log_file = open(log_file_path, 'w', encoding='utf-8')
            self._should_close = True
        self.original_stream = stream if stream is not None else sys.stdout
        
    def write(self, message):
        """Write message to both terminal and log file."""
        self.original_stream.write(message)
        self.log_file.write(message)
        self.original_stream.flush()
        self.log_file.flush()
        
    def flush(self):
        """Flush both terminal and log file."""
        self.original_stream.flush()
        self.log_file.flush()
        
    def close(self):
        """Close the log file (only if this logger opened it)."""
        if self._should_close:
            self.log_file.close()


class ValidationAction(Enum):
    """Defines the possible outcomes of a frame's validation slot."""
    PASS = 'pass'       # The response is valid and can be sent to the user.
    FIX = 'fix'         # The response has a minor issue that can be fixed programmatically.
    REVISE = 'revise'   # The response is unsuitable and requires a new LLM call with feedback.
    FAIL = 'fail'       # The response is unsalvageable; abort the turn.


class ValidationResult(TypedDict):
    """The structured output from a frame's `validate_output` method."""
    action: ValidationAction
    feedback: Optional[str]


class PromptSection(TypedDict):
    """A labeled section to be included in the system prompt.

    Used by frames to contribute structured content to the final system prompt.
    The engine assembles all sections in order.
    """
    label: str
    content: str


class FrameContext(TypedDict):
    """A dictionary holding the complete state of a single processing turn.

    This object is created by the Frame Engine at the beginning of each turn
    and is passed sequentially through each slot of every active frame. It
    acts as the central state management and data-passing mechanism.

    Attributes:
        user_input: The raw input string from the user for the current turn.
        conversation_history: A list of all previous user/assistant messages.
        frame_memory: A persistent dict for a frame to store state across turns.
        shared_context: An ephemeral dict for frames to share data within a single turn.
        prompt_sections: A list of `PromptSection` objects contributed by frames.
        system_prompt: The final assembled system prompt (built from prompt_sections).
        llm_draft_response: The raw response generated by the LLM, before validation.
        validation_results: A dict storing the `ValidationResult` from each frame.
        repair_attempts: A counter for how many times the engine has tried to
                         revise or fix an LLM response.
    """
    user_input: str
    conversation_history: list[dict[str, Any]]
    frame_memory: dict[str, Any]
    shared_context: dict[str, Any]
    prompt_sections: list[PromptSection]
    system_prompt: str
    llm_draft_response: str
    validation_results: dict[str, ValidationResult]
    repair_attempts: int


class Frame(ABC):
    """Abstract base class for all frames.

    A Frame is a modular component that encapsulates a specific AI behavior,
    policy, or interaction pattern. The Frame Engine processes a list of
    frames through the four-slot pipeline for each user turn.

    Prompt Shaping:
        Frames can contribute to the system prompt in two ways:
        1. `get_prompt_sections()`: Return labeled sections that the engine accumulates.
           This is the preferred approach for additive contributions.
        2. `shape_prompt()`: Transform the current prompt directly.
           Use this for modifications that need to see/alter the full prompt.

        The engine calls `get_prompt_sections()` first for all frames (accumulation),
        then calls `shape_prompt()` for any final transformations.
    """

    def __init__(self, **kwargs: Any) -> None:
        """Initializes the frame (optional)."""
        pass

    @property
    @abstractmethod
    def name(self) -> str:
        """Returns a unique, snake_case identifier for the frame."""
        ...

    async def analyze_input(self, context: FrameContext) -> Optional[dict[str, Any]]:
        """Slot 1: Analyzes user input and updates context before prompt shaping.

        Args:
            context: The current turn's `FrameContext`.

        Returns:
            An optional dictionary of findings to be placed in `shared_context`.
        """
        return None

    async def get_prompt_sections(self, context: FrameContext) -> list[PromptSection]:
        """Slot 2a: Returns labeled sections to be accumulated into the system prompt.

        This is the primary method for frames to contribute to the prompt.
        Each section is labeled for debuggability and assembled in frame order.

        Args:
            context: The current turn's `FrameContext`.

        Returns:
            A list of `PromptSection` objects to be added to the prompt.
            Return an empty list if this frame does not contribute sections.
        """
        return []

    async def shape_prompt(self, context: FrameContext) -> str:
        """Slot 2b: Transforms the assembled system prompt (optional).

        Called after all frames' sections have been accumulated. Use this
        for final modifications that need access to the full prompt.

        Args:
            context: The current turn's `FrameContext` with assembled `system_prompt`.

        Returns:
            The (potentially modified) system prompt.
        """
        return context['system_prompt']

    async def validate_output(self, context: FrameContext) -> ValidationResult:
        """Slot 3: Validates the LLM's draft response against the frame's rules.

        Args:
            context: The current turn's `FrameContext`, including the
                     `llm_draft_response`.

        Returns:
            A `ValidationResult` object indicating how the engine should proceed.
        """
        return {'action': ValidationAction.PASS, 'feedback': None}

    async def repair_output(self, context: FrameContext) -> str:
        """Slot 4: Attempts to programmatically fix a failed validation.

        This slot is only triggered if a frame's `validate_output` method
        returns `ValidationAction.FIX`.

        Args:
            context: The current turn's `FrameContext`.

        Returns:
            The repaired `llm_draft_response`.
        """
        return context['llm_draft_response']


class SessionLogger:
    """A centralized logger for session events.

    This logger is owned by the FrameEngine and can be used by all frames
    to log events. It saves sessions in YAML format.
    """

    def __init__(
        self,
        session_id: str,
        output_dir: Path = Path('sessions'),
    ):
        """Initializes the SessionLogger.

        Args:
            session_id: A unique identifier for the session.
            output_dir: The directory where session files will be saved.
        """
        self.session_id = session_id
        self.output_dir = output_dir
        self.entries: list[dict[str, Any]] = []
        self.metadata: dict[str, Any] = {}
        self.prompts: list[dict[str, Any]] = []  # Store prompts for JSON export
        

    def set_metadata(self, key: str, value: Any) -> None:
        """Sets metadata that will be included in the session file header."""
        self.metadata[key] = value

    def log(
        self,
        event: str,
        data: Optional[dict[str, Any]] = None,
    ) -> None:
        """Logs an event to the session.

        Args:
            event: A description of the event.
            data: Optional data associated with the event.
        """
        entry: dict[str, Any] = {
            'timestamp': datetime.now().isoformat(),
            'event': event,
        }
        if data:
            entry['data'] = data
        self.entries.append(entry)

    def log_slot(
        self,
        slot_name: str,
        frame_name: str,
        details: Optional[dict[str, Any]] = None,
    ) -> None:
        """Logs the execution of a frame slot.

        Args:
            slot_name: The name of the slot (e.g., 'analyze_input').
            frame_name: The name of the frame executing the slot.
            details: Optional details about the slot execution.
        """
        self.log(
            event=f'[{slot_name}] {frame_name}',
            data=details,
        )

    def log_turn(
        self,
        turn_number: int,
        speaker: str,
        user_message: str,
        assistant_response: str,
        analysis_data: Optional[dict[str, Any]] = None,
        metadata: Optional[dict[str, Any]] = None,
    ) -> None:
        """Logs a complete dialogue turn.

        This logs the user input and assistant response as a single turn entry.

        Args:
            turn_number: The turn number in the session.
            speaker: The name of the speaker (student).
            user_message: The user's message.
            assistant_response: The assistant's response.
            analysis_data: Optional dict with per-turn analysis from frames.
            metadata: Optional dict with turn metadata (phase, elapsed_time, etc.).
        """
        data = {
            'speaker': speaker,
            'user': user_message,
            'assistant': assistant_response,
        }
        if analysis_data:
            data['analysis'] = analysis_data
        if metadata:
            data['metadata'] = metadata

        self.log(
            event=f'Turn {turn_number}',
            data=data,
        )

    def log_prompt(
        self,
        turn_number: int,
        system_prompt: str,
        llm_draft: str,
        conversation_history: Optional[list[dict[str, Any]]] = None,
    ) -> None:
        """Logs prompts for JSON export (debugging content filters).

        Args:
            turn_number: The turn number.
            system_prompt: The full system prompt sent to LLM.
            llm_draft: The LLM's draft response.
            conversation_history: The conversation history sent with the prompt.
        """
        self.prompts.append({
            'timestamp': datetime.now().isoformat(),
            'turn': turn_number,
            'system_prompt': system_prompt,
            'llm_draft': llm_draft,
            'conversation_history': conversation_history or [],
        })

    def save(
        self,
        frame_memory: Optional[dict[str, Any]] = None,
        generate_markdown_report: bool = False,
    ) -> Path:
        """Saves the session to a YAML file and optionally a Markdown report.

        Args:
            frame_memory: Optional frame memory to include in the log.
            generate_markdown_report: If True, a human-readable Markdown
                                      report will be saved alongside the YAML file.

        Returns:
            The path to the saved YAML session file.
        """
        self.output_dir.mkdir(exist_ok=True)

        # --- Part 1: Save the standard YAML log ---
        session_data = self._build_yaml_data(frame_memory)
        yaml_file_path = self.output_dir / f'session_{self.session_id}.yaml'
        with yaml_file_path.open('w', encoding='utf-8') as f:
            yaml.dump(
                session_data,
                f,
                default_flow_style=False,
                allow_unicode=True,
                sort_keys=False,
                width=120,
            )

        # --- Part 2: Optionally save the Markdown report ---
        if generate_markdown_report:
            self._save_markdown_report(session_data, frame_memory)

        # --- Part 3: Save prompts JSON file (for debugging content filters) ---
        if self.prompts:
            json_file_path = self.output_dir / f'session_{self.session_id}_prompts.json'
            with json_file_path.open('w', encoding='utf-8') as f:
                json.dump(
                    {
                        'session_id': self.session_id,
                        'saved_at': datetime.now().isoformat(),
                        'prompts': self.prompts,
                    },
                    f,
                    indent=2,
                    ensure_ascii=False,
                )

        return yaml_file_path

    def _build_yaml_data(
        self, frame_memory: Optional[dict[str, Any]] = None
    ) -> dict[str, Any]:
        """Constructs the dictionary for YAML serialization."""
        session_data: dict[str, Any] = {
            'session_id': self.session_id,
            'saved_at': datetime.now().isoformat(),
        }

        # Include metadata
        if self.metadata:
            session_data['metadata'] = self.metadata

        # Always include all events and frame memory
        session_data['events'] = self.entries
        if frame_memory:
            session_data['frame_memory'] = frame_memory

        return session_data

    def _save_markdown_report(
        self,
        session_data: dict[str, Any],
        frame_memory: Optional[dict[str, Any]] = None,
    ) -> None:
        """Saves a human-readable summary of the session in Markdown format."""
        md_file_path = self.output_dir / f'session_{self.session_id}.md'
        with md_file_path.open('w', encoding='utf-8') as f:
            # --- Header ---
            f.write(f"# Session Report: {self.session_id}\n\n")
            f.write(f"**Saved at:** {session_data['saved_at']}\n\n")

            # --- Session Details (moved to top for better context) ---
            if self.metadata:
                f.write("## Session Details\n\n")
                for key, value in self.metadata.items():
                    f.write(f"- **{key.replace('_', ' ').title()}:** {value}\n")
                f.write("\n")

            # --- Mnemonic Type Section ---
            mnemonic_type = self.metadata.get('mnemonic_type', 'Unknown')
            type_descriptions = {
                "Story": "A narrative that weaves concepts together",
                "Poem": "Rhyming lines that capture key concepts",
                "Jokes": "Humorous setups and punchlines about concepts",
            }
            type_desc = type_descriptions.get(mnemonic_type, "A creative mnemonic device")
            f.write("## 🎨 Mnemonic Type\n\n")
            f.write(f"**{mnemonic_type}** - {type_desc}\n\n")

            # --- Phase Transitions (exact copy of terminal output) ---
            if frame_memory:
                phase_transitions = frame_memory.get('_phase_transitions', [])
                if phase_transitions:
                    f.write("## ⏱️ Phase Transitions\n\n")
                    for transition in phase_transitions:
                        phase = transition.get('phase', 'N/A')
                        turn = transition.get('turn', 'N/A')
                        elapsed_time = transition.get('elapsed_time', 0)
                        f.write(f"🔄 PHASE TRANSITION: Entered Phase {phase} at Turn {turn} ({elapsed_time:.1f} min)\n")
                    f.write("\n")

            # --- Participation Summary ---
            if frame_memory:
                balanced_turns_memory = frame_memory.get('balanced_turns_validator', {})
                participation = balanced_turns_memory.get('participation', {})
                if participation:
                    f.write("## 📊 Participation Summary\n\n")
                    f.write("| Student | Contributions | Speaking Time |\n")
                    f.write("|---------|---------------|---------------|\n")
                    for student, p_data in sorted(participation.items()):
                        count = p_data.get('contribution_count', 0)
                        time = p_data.get('total_speaking_time_seconds', 0)
                        f.write(f"| **{student}** | {count} | {time:.1f}s |\n")
                    f.write("\n")
            
            # --- Comprehension Summary ---
            if frame_memory:
                comprehension_memory = frame_memory.get('comprehension_tracker', {})
                by_student = comprehension_memory.get('by_student', {})
                if by_student:
                    f.write("## 🧠 Comprehension Summary\n\n")
                    for student_name in sorted(by_student.keys()):
                        student_concepts = by_student[student_name]
                        understood = []
                        confused = []
                        for concept, data in student_concepts.items():
                            level = data.get('level', 'not_seen')
                            if level == 'understood':
                                understood.append(concept)
                            elif level == 'confused':
                                confused.append(concept)
                        if understood or confused:
                            f.write(f"### {student_name}\n\n")
                            if understood:
                                f.write(f"**✅ Understood:** {', '.join(understood)}\n\n")
                            if confused:
                                f.write(f"**❓ Confused:** {', '.join(confused)}\n\n")

            # --- Selected Concepts ---
            if frame_memory:
                mnemonic_state = frame_memory.get('mnemonic_state', {})
                selected_concepts = mnemonic_state.get('selected_concepts', [])
                concepts_finalized = mnemonic_state.get('concepts_finalized', False)
                f.write("## 🎯 Selected Concepts\n\n")
                if selected_concepts:
                    f.write(f"**Status:** {'✅ Finalized' if concepts_finalized else '⏳ In Progress'}\n\n")
                    for i, concept in enumerate(selected_concepts, 1):
                        f.write(f"{i}. {concept}\n")
                    f.write("\n")
                else:
                    f.write("**Status:** ❌ No concepts selected\n\n")

            # --- Created Mnemonic ---
            if frame_memory:
                mnemonic_state = frame_memory.get('mnemonic_state', {})
                mnemonic_text = mnemonic_state.get('mnemonic_text_clean') or mnemonic_state.get('mnemonic_text', '')
                mnemonic_created = mnemonic_state.get('mnemonic_created', False)
                f.write("## 📖 Created Mnemonic\n\n")
                if mnemonic_text and mnemonic_created:
                    f.write("**Status:** ✅ Complete\n\n")
                    f.write(f"{mnemonic_text}\n\n")
                else:
                    f.write("**Status:** ❌ No mnemonic created\n\n")

            # --- Conversation Log ---
            f.write("## Conversation Log\n\n")
            turn_events = [
                e for e in self.entries if e['event'].startswith('Turn')
            ]
            # Sort numerically by extracting turn number, not alphabetically
            for event in sorted(turn_events, key=lambda x: int(x['event'].split()[1])):
                data = event.get('data', {})
                turn_str = event['event']
                timestamp = event.get('timestamp', '')
                speaker = data.get('speaker', 'Unknown')
                user_msg = data.get('user', '')
                assistant_msg = data.get('assistant', '')

                # Write turn header with timestamp if available
                f.write(f"### {turn_str}")
                if timestamp:
                    f.write(f" ({timestamp})")
                f.write("\n\n")

                # --- Add Phase Tracker metadata to each turn ---
                metadata = data.get('metadata', {})
                if metadata:
                    phase = metadata.get('session_phase')
                    elapsed = metadata.get('elapsed_time_minutes')
                    if phase is not None and elapsed is not None:
                        f.write(f"**Phase:** {phase}/3\n")
                        f.write(f"**Elapsed Time:** {elapsed:.1f} min\n\n")

                f.write(f"**{speaker}:** {user_msg}\n\n")

                # Display the per-turn comprehension analysis if it exists
                analysis = data.get('analysis', {})
                per_turn_comp = analysis.get('_per_turn_comprehension', {})
                understood = per_turn_comp.get('understood', [])
                confused = per_turn_comp.get('confused', [])

                if understood or confused:
                    f.write("<details>\n<summary>Turn Analysis</summary>\n\n")
                    if understood:
                        f.write(f"- **Understood:** {', '.join(understood)}\n")
                    if confused:
                        f.write(f"- **Confused:** {', '.join(confused)}\n")
                    f.write("\n</details>\n\n")

                # Add metadata if available (phase, elapsed time, etc.)
                metadata = data.get('metadata', {})
                if metadata:
                    f.write("<details>\n<summary>Response Metadata</summary>\n\n")
                    for key, value in metadata.items():
                        f.write(f"- **{key.replace('_', ' ').title()}:** {value}\n")
                    f.write("\n</details>\n\n")

                f.write(f"**Marty:** {assistant_msg}\n\n")
                f.write("---\n\n")
            
            # --- Append Terminal Log Content ---
            if hasattr(self, '_shared_log_file') and self._shared_log_file:
                # Remove logging handler and flush/close the terminal log file
                if hasattr(self, '_log_handler') and self._log_handler:
                    try:
                        self._log_handler.flush()
                        logging.getLogger().removeHandler(self._log_handler)
                        self._log_handler.close()
                    except Exception:
                        pass
                
                try:
                    self._shared_log_file.flush()
                    self._shared_log_file.close()
                except Exception:
                    pass
                
                # Read the terminal log content
                terminal_log_path = self.output_dir / f"session_{self.session_id}_terminal_log.md"
                if terminal_log_path.exists():
                    terminal_content = terminal_log_path.read_text(encoding='utf-8')
                    if terminal_content.strip():
                        f.write("## 🖥️ System Log\n\n")
                        f.write("```\n")
                        f.write(terminal_content)
                        f.write("```\n\n")
                    
                    # Delete the separate terminal log file
                    try:
                        terminal_log_path.unlink()
                    except Exception:
                        pass
                    
                    # Also clean up any orphan terminal log files from incomplete sessions
                    for orphan_log in self.output_dir.glob('*_terminal_log.md'):
                        try:
                            orphan_log.unlink()
                        except Exception:
                            pass
